name: Check
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Format
        run: deno fmt && git diff-index --quiet HEAD
      - name: Lint
        run: deno lint && git diff-index --quiet HEAD
